In [226]:
import pandas as pd
import numpy as np
import sklearn 

from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# load dataset
pima = pd.read_csv("speedDating_trab.csv")

pima.head(10)


Unnamed: 0   id  partner   age  age_o  goal  date  go_out  int_corr  \
0           1  1.0        1  21.0   27.0   2.0   7.0     1.0      0.14   
1           2  1.0        2  21.0   22.0   2.0   7.0     1.0      0.54   
2           3  1.0        3  21.0   22.0   2.0   7.0     1.0      0.16   
3           4  1.0        4  21.0   23.0   2.0   7.0     1.0      0.61   
4           5  1.0        5  21.0   24.0   2.0   7.0     1.0      0.21   
5           6  1.0        6  21.0   25.0   2.0   7.0     1.0      0.25   
6           7  1.0        7  21.0   30.0   2.0   7.0     1.0      0.34   
7           8  1.0        8  21.0   27.0   2.0   7.0     1.0      0.50   
8           9  1.0        9  21.0   28.0   2.0   7.0     1.0      0.28   
9          10  1.0       10  21.0   24.0   2.0   7.0     1.0     -0.36   

   length  met  like  prob  match  
0     2.0  1.0   7.0   6.0      0  
1     2.0  1.0   7.0   5.0      0  
2     2.0  1.0   7.0   NaN      1  
3     2.0  1.0   7.0   6.0      1  
4     2.0  1.0   6.0   6.0      1  
5     2.0  1.0   6.0   5.0      0  
6     2.0  1.0   6.0   5.0      0  
7     2.0  NaN   6.0   7.0      0  
8     2.0  1.0   7.0   7.0      1  
9     2.0  1.0   6.0   6.0      0

In [227]:
pima

Unnamed: 0    id  partner   age  age_o  goal  date  go_out  int_corr  \
0              1   1.0        1  21.0   27.0   2.0   7.0     1.0      0.14   
1              2   1.0        2  21.0   22.0   2.0   7.0     1.0      0.54   
2              3   1.0        3  21.0   22.0   2.0   7.0     1.0      0.16   
3              4   1.0        4  21.0   23.0   2.0   7.0     1.0      0.61   
4              5   1.0        5  21.0   24.0   2.0   7.0     1.0      0.21   
...          ...   ...      ...   ...    ...   ...   ...     ...       ...   
8373        8374  22.0       18  25.0   26.0   1.0   2.0     1.0      0.64   
8374        8375  22.0       19  25.0   24.0   1.0   2.0     1.0      0.71   
8375        8376  22.0       20  25.0   29.0   1.0   2.0     1.0     -0.46   
8376        8377  22.0       21  25.0   22.0   1.0   2.0     1.0      0.62   
8377        8378   NaN       22  25.0   22.0   1.0   2.0     1.0      0.01   

      length  met  like  prob  match  
0        2.0  1.0   7.0   6.0      0  
1        2.0  1.0   7.0   5.0      0  
2        2.0  1.0   7.0   NaN      1  
3        2.0  1.0   7.0   6.0      1  
4        2.0  1.0   6.0   6.0      1  
...      ...  ...   ...   ...    ...  
8373     1.0  0.0   2.0   5.0      0  
8374     1.0  0.0   4.0   4.0      0  
8375     1.0  0.0   6.0   5.0      0  
8376     1.0  0.0   5.0   5.0      0  
8377     1.0  0.0   4.0   5.0      0  

[8378 rows x 14 columns]

In [228]:
pima.isnull().sum()

Unnamed: 0      0
id              1
partner         0
age            95
age_o         104
goal           79
date           97
go_out         79
int_corr      158
length        915
met           375
like          240
prob          309
match           0
dtype: int64

In [229]:
#tds os nans de tds as colunas menos o int_corr vamos preencher com a moda
#o int_corr preenchemos com a media

gf= pima['prob'].mode()[0]
pima['prob'].fillna(value=gf,inplace=True)

gf= pima['like'].mode()[0]
pima['like'].fillna(value=gf,inplace=True)

gf= pima['met'].mode()[0]
pima['met'].fillna(value=gf,inplace=True)

gf= pima['length'].mode()[0]
pima['length'].fillna(value=gf,inplace=True)

gf= pima['int_corr'].mean()
pima['int_corr'].fillna(value=gf,inplace=True)

gf= pima['go_out'].mode()[0]
pima['go_out'].fillna(value=gf,inplace=True)

gf= pima['date'].mode()[0]
pima['date'].fillna(value=gf,inplace=True)

gf= pima['goal'].mode()[0]
pima['goal'].fillna(value=gf,inplace=True)

gf= pima['age_o'].mode()[0]
pima['age_o'].fillna(value=gf,inplace=True)

gf= pima['age'].mode()[0]
pima['age'].fillna(value=gf,inplace=True)

#gf= pima['id'].mode()[0]
#pima['id'].fillna(value=gf,inplace=True)
pima.dropna(subset=['id'],inplace=True )




In [230]:
pima

Unnamed: 0    id  partner   age  age_o  goal  date  go_out  int_corr  \
0              1   1.0        1  21.0   27.0   2.0   7.0     1.0      0.14   
1              2   1.0        2  21.0   22.0   2.0   7.0     1.0      0.54   
2              3   1.0        3  21.0   22.0   2.0   7.0     1.0      0.16   
3              4   1.0        4  21.0   23.0   2.0   7.0     1.0      0.61   
4              5   1.0        5  21.0   24.0   2.0   7.0     1.0      0.21   
...          ...   ...      ...   ...    ...   ...   ...     ...       ...   
8372        8373  22.0       17  25.0   24.0   1.0   2.0     1.0      0.28   
8373        8374  22.0       18  25.0   26.0   1.0   2.0     1.0      0.64   
8374        8375  22.0       19  25.0   24.0   1.0   2.0     1.0      0.71   
8375        8376  22.0       20  25.0   29.0   1.0   2.0     1.0     -0.46   
8376        8377  22.0       21  25.0   22.0   1.0   2.0     1.0      0.62   

      length  met  like  prob  match  
0        2.0  1.0   7.0   6.0      0  
1        2.0  1.0   7.0   5.0      0  
2        2.0  1.0   7.0   5.0      1  
3        2.0  1.0   7.0   6.0      1  
4        2.0  1.0   6.0   6.0      1  
...      ...  ...   ...   ...    ...  
8372     1.0  0.0   4.0   4.0      0  
8373     1.0  0.0   2.0   5.0      0  
8374     1.0  0.0   4.0   4.0      0  
8375     1.0  0.0   6.0   5.0      0  
8376     1.0  0.0   5.0   5.0      0  

[8377 rows x 14 columns]

In [231]:
#convertemos de float para int
pima[['prob','like','met','length','go_out','date','goal','age_o','age','id']]=  pima[['prob','like','met','length','go_out','date','goal','age_o','age','id']].astype(int)

pima.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 8377 entries, 0 to 8376
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  8377 non-null   int64  
 1   id          8377 non-null   int64  
 2   partner     8377 non-null   int64  
 3   age         8377 non-null   int64  
 4   age_o       8377 non-null   int64  
 5   goal        8377 non-null   int64  
 6   date        8377 non-null   int64  
 7   go_out      8377 non-null   int64  
 8   int_corr    8377 non-null   float64
 9   length      8377 non-null   int64  
 10  met         8377 non-null   int64  
 11  like        8377 non-null   int64  
 12  prob        8377 non-null   int64  
 13  match       8377 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 981.7 KB


In [232]:
#numero de 1's
print("% 1's:",pima['match'].mean())
print("% 0's:", 1-pima['match'].mean())


% 1's: 0.16473677927659067
% 0's: 0.8352632207234093


In [233]:
pima.isnull().sum()

Unnamed: 0    0
id            0
partner       0
age           0
age_o         0
goal          0
date          0
go_out        0
int_corr      0
length        0
met           0
like          0
prob          0
match         0
dtype: int64

In [234]:
pima.head(10)

Unnamed: 0  id  partner  age  age_o  goal  date  go_out  int_corr  length  \
0           1   1        1   21     27     2     7       1      0.14       2   
1           2   1        2   21     22     2     7       1      0.54       2   
2           3   1        3   21     22     2     7       1      0.16       2   
3           4   1        4   21     23     2     7       1      0.61       2   
4           5   1        5   21     24     2     7       1      0.21       2   
5           6   1        6   21     25     2     7       1      0.25       2   
6           7   1        7   21     30     2     7       1      0.34       2   
7           8   1        8   21     27     2     7       1      0.50       2   
8           9   1        9   21     28     2     7       1      0.28       2   
9          10   1       10   21     24     2     7       1     -0.36       2   

   met  like  prob  match  
0    1     7     6      0  
1    1     7     5      0  
2    1     7     5      1  
3    1     7     6      1  
4    1     6     6      1  
5    1     6     5      0  
6    1     6     5      0  
7    0     6     7      0  
8    1     7     7      1  
9    1     6     6      0

In [235]:
#import tensorflow as tf

#np.random.seed(1234)
#tf.random.set_random_seed(1234)
#dropamos a tabela int_corr pq é irrelevante neste momento
pima = pima.drop('int_corr',1)

#divisao do cassos em q tem match e os q n tem match
resultados = pima['match']
dados = pima.drop(['match'],axis=1)


# Split dataset into training set and test set (30%/70%)
dados_treino, dados_teste, resultados_treino, resultados_teste= train_test_split( dados, resultados, test_size=0.3,random_state=1)

In [236]:
pima.head(10)

Unnamed: 0  id  partner  age  age_o  goal  date  go_out  length  met  like  \
0           1   1        1   21     27     2     7       1       2    1     7   
1           2   1        2   21     22     2     7       1       2    1     7   
2           3   1        3   21     22     2     7       1       2    1     7   
3           4   1        4   21     23     2     7       1       2    1     7   
4           5   1        5   21     24     2     7       1       2    1     6   
5           6   1        6   21     25     2     7       1       2    1     6   
6           7   1        7   21     30     2     7       1       2    1     6   
7           8   1        8   21     27     2     7       1       2    0     6   
8           9   1        9   21     28     2     7       1       2    1     7   
9          10   1       10   21     24     2     7       1       2    1     6   

   prob  match  
0     6      0  
1     5      0  
2     5      1  
3     6      1  
4     6      1  
5     5      0  
6     5      0  
7     7      0  
8     7      1  
9     6      0

In [237]:
#CART COM IMPUREZAS DE GINI

# Create Decision Tree classifer object
clf2 = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf2 = clf2.fit(dados_treino, resultados_treino)

#Predict the response for test dataset
predicted_test2= clf2.predict(dados_teste)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(resultados_teste, predicted_test2))

print("Mean Absolute Error:",mae(resultados_teste,clf2.predict(dados_teste)))

print("Mean Squared Error:",mse(resultados_teste,clf2.predict(dados_teste)))


Accuracy: 0.7804295942720764
Mean Absolute Error: 0.21957040572792363
Mean Squared Error: 0.21957040572792363


In [238]:
#MATRIZ DE CONFUSÃO
confusion_matrix(resultados_teste, clf2.predict( dados_teste))

array([[1803,  286],
       [ 266,  159]])

In [239]:
#ID3 COM ENTROPIA
# Create Decision Tree classifer object
clf = DecisionTreeClassifier(criterion="entropy")

# Train Decision Tree Classifer
clf = clf.fit(dados_treino, resultados_treino)

#Predict the response for test dataset
predicted_test = clf.predict(dados_teste)



In [240]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(resultados_teste, predicted_test))

print("Mean Absolute Error:",mae(resultados_teste,clf.predict(dados_teste)))

print("Mean Squared Error:",mse(resultados_teste,clf.predict(dados_teste)))

Accuracy: 0.7756563245823389
Mean Absolute Error: 0.2243436754176611
Mean Squared Error: 0.2243436754176611


In [241]:

confusion_matrix(resultados_teste, clf.predict( dados_teste))

array([[1805,  284],
       [ 280,  145]])

In [242]:

print(classification_report(resultados_teste, clf.predict(dados_teste)))

              precision    recall  f1-score   support

           0       0.87      0.86      0.86      2089
           1       0.34      0.34      0.34       425

    accuracy                           0.78      2514
   macro avg       0.60      0.60      0.60      2514
weighted avg       0.78      0.78      0.78      2514



In [243]:
#NAIVE BAYES
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(dados_treino,resultados_treino)

#Predict the response for test dataset
predicted3 = gnb.predict(dados_teste)
print("Accuracy:",metrics.accuracy_score(resultados_teste, predicted3))

from sklearn.metrics import mean_absolute_error as mae
print("Mean Absolute Error:",mae(resultados_teste,gnb.predict(dados_teste)))
from sklearn.metrics import mean_squared_error as mse
print("Mean Squared Error:",mse(resultados_teste,gnb.predict(dados_teste)))

Accuracy: 0.8214001591089897
Mean Absolute Error: 0.17859984089101033
Mean Squared Error: 0.17859984089101033


In [244]:

confusion_matrix(resultados_teste, gnb.predict( dados_teste))

array([[1956,  133],
       [ 316,  109]])

In [221]:

print(classification_report(resultados_teste, gnb.predict(dados_teste)))

              precision    recall  f1-score   support

           0       0.87      0.94      0.91      2109
           1       0.48      0.27      0.34       405

    accuracy                           0.84      2514
   macro avg       0.68      0.61      0.62      2514
weighted avg       0.81      0.84      0.82      2514



In [222]:
#comparar com o random Forest

from sklearn.ensemble import RandomForestClassifier # Import Decision Tree Classifier
# Create Decision Tree classifer object
clf2 = RandomForestClassifier()

# Train Decision Tree Classifer
clf2 = clf2.fit(dados_treino, resultados_treino)

#Predict the response for test dataset
predicted2 = clf2.predict(dados_teste)

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(resultados_teste, predicted2))

Accuracy: 0.8480509148766905


In [223]:
#CART COM REGRESSOR
from sklearn.tree import DecisionTreeRegressor 
# create a regressor object
regressor = DecisionTreeRegressor() 
  
# fit the regressor with X and Y data
regressor.fit(dados_treino, resultados_treino)
predict = regressor.predict(dados_teste)
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(resultados_teste, predict))

print("Mean Absolute Error:",mae(resultados_teste,regressor.predict(dados_teste)))

print("Mean Squared Error:",mse(resultados_teste,regressor.predict(dados_teste)))

Accuracy: 0.7756563245823389
Mean Absolute Error: 0.2243436754176611
Mean Squared Error: 0.2243436754176611


In [224]:

confusion_matrix(resultados_teste, regressor.predict( dados_teste))

array([[1804,  305],
       [ 259,  146]])

In [225]:

print(classification_report(resultados_teste, regressor.predict(dados_teste)))

              precision    recall  f1-score   support

           0       0.87      0.86      0.86      2109
           1       0.32      0.36      0.34       405

    accuracy                           0.78      2514
   macro avg       0.60      0.61      0.60      2514
weighted avg       0.79      0.78      0.78      2514

